spring:
  data:
    mongodb:
      username: alex
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092\
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.alexgiou.ecommerce.kafka.OrderConfirmation, paymentConfirmation:com.alexgiou.ecommerce.notification.PaymentNotificationRequest
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: alex
    password: password
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connection:
          timeout: 5000
        write:
          timeout: 5000
server:
  port: 8040
